### ISSUE TITLE
BetterMediaPlayer [Could not be compiled

### ISSUE THREAD

**Issue by dragonunitedtm** [jaspwr/BDPlugins#3]
TypeError: Cannot read property 'Controls' of undefined
at plugin (betterdiscord://plugins/BetterMediaPlayer.plugin.js:195:67)
at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:489:16)
at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:490:7)
at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:491:3)
at Object.requireAddon (<anonymous>:4:39192)
at Object.loadAddon (<anonymous>:4:9163)
at Object.loadAddon (<anonymous>:4:36864)
at Object.loadAllAddons (<anonymous>:4:11637)
at Object.initialize (<anonymous>:4:6059)
at Object.initialize (<anonymous>:4:36059)
at Object.startup (<anonymous>:4:396505)

**Comment by dragonunitedtm** [comment]
TypeError: Cannot read property 'Controls' of undefined
at plugin (betterdiscord://plugins/BetterMediaPlayer.plugin.js:195:67)
at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:489:16)
at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:490:7)
at eval (betterdiscord://plugins/BetterMediaPlayer.plugin.js:491:3)
at Object.requireAddon (<anonymous>:4:39192)
at Object.loadAddon (<anonymous>:4:9163)
at Object.loadAddon (<anonymous>:4:36864)
at Object.loadAllAddons (<anonymous>:4:11637)
at Object.initialize (<anonymous>:4:6059)
at Object.initialize (<anonymous>:4:36059)
at Object.startup (<anonymous>:4:396505)

**Comment by jaspwr** [comment]
This isn't my plugin. This is the repo you're looking for https://github.com/unknown81311/BetterMediaPlayer
